name: autotests

on:
  push:
    branches:
      - "master"
    paths:
      - "**.ts"
      - "**.json"
  pull_request:
    branches:
      - "master"

jobs:
  autotests:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.14.0"
      - run: npm install
      - run: npx playwright install chromium --with-deps
      - run: cp .env.sample .env
      - run: npm run e2e
        env:
          GB_USER_LOGIN: ${{ vars.GB_USER_LOGIN }}
          GB_USER_PASSWORD: ${{ secrets.GB_USER_PASSWORD }}
      - uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20
      - name: Publish Allure report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
